
export const UPDATE_IS_MENU = 'UPDATE_IS_MENU'

export const UPDATE_OVERLAY_VISIBLE = 'UPDATE_OVERLAY_VISIBLE'

export const UPDATE_PAGE_VIEW = 'UPDATE_PAGE_VIEW'

export const UPDATE_FOOT_MENU = 'UPDATE_FOOT_MENU'

export const UPDATE_IS_OVERLAY_VISIBLE = 'UPDATE_IS_OVERLAY_VISIBLE'

export const UPDATE_SELECT_CITY = 'UPDATE_SELECT_CITY'

export const UPDATE_IS_CITY_PICKER = 'UPDATE_IS_CITY_PICKER'

export const UPDATE_CART_NUM = 'UPDATE_CART_NUM'

export const UPDATE_SLIDER_MENU = 'UPDATE_SLIDER_MENU'

export const UPDATE_SCROLL_VIEW = 'UPDATE_SCROLL_VIEW'

export const UPDATE_SCROLL_PICKER = 'UPDATE_SCROLL_PICKER'
